const Tests = [
  {
    title: 'QA Defalut Test AM',
    uuid:"998b8cbd-3cf0-454a-9df3-fa458032f231",
    description: 'Lorem ipsum',
    courseId: null,
    language: 'am',
    type: 'QA',
    time: '20',
    percent: 75,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: 'QA Defalut Test EN',
    uuid:"998b8cbd-3cf0-454a-9df3-fa458032f231",
    description: 'Lorem ipsum',
    courseId: null,
    language: 'en',
    type: 'QA',
    time: '20',
    percent: 75,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: 'QA Defalut Test RU',
    uuid:"998b8cbd-3cf0-454a-9df3-fa458032f231",
    description: 'Lorem ipsum',
    courseId: null,
    language: 'ru',
    type: 'QA',
    time: '20',
    percent: 75,
    createdAt: new Date(),
    updatedAt: new Date(),
  },  {
    title: 'LOGIC Defalut Test AM',
    uuid:"1670aca1-edaf-4cef-9658-0616cd0cf792",
    description: 'Lorem ipsum',
    courseId: null,
    language: 'am',
    type: 'LOGIC',
    time: '20',
    percent: 75,
    createdAt: new Date(),
    updatedAt: new Date(),
  },  {
    title: 'LOGIC Defalut Test en',
    uuid:"1670aca1-edaf-4cef-9658-0616cd0cf792",
    description: 'Lorem ipsum',
    courseId: null,
    language: 'en',
    type: 'LOGIC',
    time: '20',
    percent: 75,
    createdAt: new Date(),
    updatedAt: new Date(),
  },  {
    title: 'LOGIC Defalut Test RU',
    uuid:"1670aca1-edaf-4cef-9658-0616cd0cf792",
    description: 'Lorem ipsum',
    courseId: null,
    language: 'ru',
    type: 'LOGIC',
    time: '20',
    percent: 75,
    createdAt: new Date(),
    updatedAt: new Date(),
  },  {
    title: 'ENGLISH Defalut Test',
    description: 'Lorem ipsum',
    uuid:"17103799-3656-4377-88b3-99d71da5a3f4",
    courseId: null,
    language: 'en',
    type: 'ENGLISH',
    time: '20',
    percent: 75,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const TestsQuizz = [
  {
    question: 'Lorem Ipsum',
    testId: 1,
    language: 'am',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: 'Lorem Ipsum',
    testId: 2,
    language: 'am',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: 'Lorem Ipsum',
    testId: 3,
    language: 'am',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const TestsQuizzOption = [
  {
    questionId: 1,
    option: '1 Option incorrect',
    isCorrect: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    questionId: 1,
    option: '2 Option incorrect',
    isCorrect: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    questionId: 1,
    option: '3 Option correct',
    isCorrect: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    questionId: 1,
    option: '4 Option incorrect',
    isCorrect: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    questionId: 2,
    option: '1 Option incorrect',
    isCorrect: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    questionId: 2,
    option: '2 Option incorrect',
    isCorrect: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    questionId: 2,
    option: '3 Option correct',
    isCorrect: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    questionId: 2,
    option: '4 Option incorrect',
    isCorrect: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    questionId: 3,
    option: '1 Option incorrect',
    isCorrect: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    questionId: 3,
    option: '2 Option incorrect',
    isCorrect: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    questionId: 3,
    option: '3 Option correct',
    isCorrect: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    questionId: 3,
    option: '4 Option incorrect',
    isCorrect: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = {
  Tests,
  TestsQuizz,
  TestsQuizzOption,
};
