const jwt = require("jsonwebtoken")
require("dotenv").config();

const Users = [
  {
    firstName: "John",
    lastName: "Smith",
    email: "JohnSmith@gmail.com",
    phoneNumber: "+37499887766",
    birthday: new Date(),
    gender: "Male",
    country: "USA",
    city: "New York",
    englishLevel: "C1",
    education: "Harvard",
    backgroundInQA: true,
    password: "$2b$10$d3ZAK4YSEfUf4PQszTO7Bea9fVes5MRiQyP4EPhuRmx..EDeXWWri",
    likedCourses: [1],
    isVerified: true,
    role: "STUDENT",
    token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiU1RVREVOVCIsImVtYWlsIjoiYmRiZTU4MDE5ODVAY3JpbmdlbW9uc3Rlci5jb20iLCJpYXQiOjE2OTU4MDIwNzZ9.HypxfsZn6hU4tUkzS0iHF0Y1wEfxNmWXCWUFMQmUYMM",
    tokenCreatedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "John",
    lastName: "Wick",
    email: "JohnWick@gmail.com",
    phoneNumber: "+37499887755",
    birthday: new Date(),
    gender: "Male",
    country: "USA",
    city: "New York",
    englishLevel: "C1",
    education: "Harvard",
    backgroundInQA: true,
    password: "$2b$10$d3ZAK4YSEfUf4PQszTO7Bea9fVes5MRiQyP4EPhuRmx..EDeXWWri",
    likedCourses: [1],
    isVerified: true,
    role: "STUDENT",
    token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJyb2xlIjoiU1RVREVOVCIsImVtYWlsIjoiNzZjNDU4MDIyMDhAYmVhY29ubWVzc2VuZ2VyLmNvbSIsImlhdCI6MTY5NTgwMjI2OH0.X40oUGqe7Og-WtfJN6ALcgbiR7TxJWW17xulzvM0mUU",
    tokenCreatedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Sarah",
    lastName: "Smith",
    email: "Sarah@gmail.com",
    phoneNumber: "+37499887755",
    birthday: new Date(),
    gender: "Male",
    country: "USA",
    city: "New York",
    englishLevel: "C1",
    education: "Harvard",
    backgroundInQA: true,
    password: "$2b$10$d3ZAK4YSEfUf4PQszTO7Bea9fVes5MRiQyP4EPhuRmx..EDeXWWri",
    likedCourses: [1],
    isVerified: true,
    role: "STUDENT",
    token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6Inp1Y3dkaGtzdnFsdEBkaWdpbmV5LmNvbSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNjk2NTI2OTAyfQ.7YwtxgZAc8ICNrn9eglGlPQGfefSCjSnXqAVcppuxrg",
    tokenCreatedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Teacher",
    lastName: "Teacher",
    email: "Teacher@gmail.com",
    phoneNumber: "+37499887755",
    birthday: new Date(),
    gender: "Male",
    country: "USA",
    city: "New York",
    englishLevel: "C1",
    education: "Harvard",
    backgroundInQA: true,
    password: "$2b$10$d3ZAK4YSEfUf4PQszTO7Bea9fVes5MRiQyP4EPhuRmx..EDeXWWri",
    likedCourses: [1],
    isVerified: true,
    role: "TEACHER",
    token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJlbWFpbCI6InVuYnp3bmtuZ3ljZ29AaGxkcml2ZS5jb20iLCJyb2xlIjoiVEVBQ0hFUiIsImlhdCI6MTY5NjU4ODQwM30.3TKWHk7Tt94s2To40ftW5t2geSgoXEGZKaDqfsWgE7Q",
    tokenCreatedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Admin",
    lastName: "Smith",
    email: "Admin@gmail.com",
    phoneNumber: "+37499887766",
    birthday: new Date(),
    gender: "Male",
    country: "USA",
    city: "New York",
    englishLevel: "C1",
    education: "Harvard",
    backgroundInQA: true,
    password: "$2b$10$d3ZAK4YSEfUf4PQszTO7Bea9fVes5MRiQyP4EPhuRmx..EDeXWWri",
    likedCourses: [1],
    isVerified: true,
    role: "ADMIN",
    token:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJlbWFpbCI6IkFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcwNTMwNTc0NH0.hITNb2a0e9yygTPe57bfkyyz3Etd6EzniF_MKJ6mbaA",
    tokenCreatedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = {
  Users,
};
