const jwt = require("jsonwebtoken");
require("dotenv").config();

const Users = [
  {
    firstName: "John",
    lastName: "Smith",
    email: "JohnSmith@gmail.com",
    phoneNumber: "+37499887766",
    birthday: "2000-10-04T19:00:00.000Z",
    gender: "Male",
    country: "USA",
    city: "New York",
    englishLevel: "C1",
    education: "Harvard",
    backgroundInQA: true,
    password: "$2b$10$d3ZAK4YSEfUf4PQszTO7Bea9fVes5MRiQyP4EPhuRmx..EDeXWWri",
    likedCourses: [1],
    isVerified: true,
    role: "STUDENT",
    image: "defaultIcon.png",
    token:
      "eyJ1c2VyX2lkIjoxLCJlbWFpbCI6IkpvaG5TbWl0aEBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImFsZyI6IkhTMjU2In0.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.hq9bc0RlpbktcMDG8WFa25gt44aMT-jfE8DDaIClGlk",
    tokenCreatedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "John",
    lastName: "Wick",
    email: "JohnWick@gmail.com",
    phoneNumber: "+37499887755",
    birthday: "2000-10-04T19:00:00.000Z",
    gender: "Male",
    country: "USA",
    city: "New York",
    englishLevel: "C1",
    education: "Harvard",
    backgroundInQA: true,
    password: "$2b$10$d3ZAK4YSEfUf4PQszTO7Bea9fVes5MRiQyP4EPhuRmx..EDeXWWri",
    likedCourses: [1],
    isVerified: true,
    role: "STUDENT",
    image: "TestIcon.png",
    token:
      "eyJ1c2VyX2lkIjoyLCJlbWFpbCI6IkpvaG5XaWNrQGdtYWlsLmNvbSIsInJvbGUiOiJTVFVERU5UIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.XfzHfPjlpmj8Ws1D4BCuZo7TiwR0TPx23nCea2aoWF8",
    tokenCreatedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Sarah",
    lastName: "Smith",
    email: "Sarah@gmail.com",
    phoneNumber: "+37499887755",
    birthday: "2000-10-04T19:00:00.000Z",
    gender: "Male",
    country: "USA",
    city: "New York",
    englishLevel: "C1",
    education: "Harvard",
    backgroundInQA: true,
    password: "$2b$10$d3ZAK4YSEfUf4PQszTO7Bea9fVes5MRiQyP4EPhuRmx..EDeXWWri",
    likedCourses: [1],
    isVerified: true,
    role: "STUDENT",
    image: "defaultIcon.png",
    token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6Inp1Y3dkaGtzdnFsdEBkaWdpbmV5LmNvbSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNjk2NTI2OTAyfQ.7YwtxgZAc8ICNrn9eglGlPQGfefSCjSnXqAVcppuxrg",
    tokenCreatedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Teacher",
    lastName: "Teacher",
    email: "Teacher@gmail.com",
    phoneNumber: "+37499887755",
    birthday: "2000-10-04T19:00:00.000Z",
    gender: "Male",
    country: "USA",
    city: "New York",
    englishLevel: "C1",
    education: "Harvard",
    backgroundInQA: true,
    password: "$2b$10$d3ZAK4YSEfUf4PQszTO7Bea9fVes5MRiQyP4EPhuRmx..EDeXWWri",
    likedCourses: [1],
    isVerified: true,
    role: "TEACHER",
    image: "TestIcon.png",
    token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJlbWFpbCI6InVuYnp3bmtuZ3ljZ29AaGxkcml2ZS5jb20iLCJyb2xlIjoiVEVBQ0hFUiIsImlhdCI6MTY5NjU4ODQwM30.3TKWHk7Tt94s2To40ftW5t2geSgoXEGZKaDqfsWgE7Q",
    tokenCreatedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Admin",
    lastName: "Smith",
    email: "Admin@gmail.com",
    phoneNumber: "+37499887766",
    birthday: "2000-10-04T19:00:00.000Z",
    gender: "Male",
    country: "USA",
    city: "New York",
    englishLevel: "C1",
    education: "Harvard",
    backgroundInQA: true,
    password: "$2b$10$d3ZAK4YSEfUf4PQszTO7Bea9fVes5MRiQyP4EPhuRmx..EDeXWWri",
    likedCourses: [1],
    isVerified: true,
    role: "ADMIN",

    image: "defaultIcon.png",
    token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJlbWFpbCI6IkFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcwNTMwNTc0NH0.hITNb2a0e9yygTPe57bfkyyz3Etd6EzniF_MKJ6mbaA",
    tokenCreatedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = {
  Users,
};
