const Users = [
  {
    firstName: "John",
    lastName: "Smith",
    email: "JohnSmith@gmail.com",
    phoneNumber: "+37499887766",
    birthday: new Date(),
    gender: "Male",
    country: "USA",
    city: "New York",
    englishLevel: "C1",
    education: "Harvard",
    backgroundInQA: true,
    password: "$2b$10$d3ZAK4YSEfUf4PQszTO7Bea9fVes5MRiQyP4EPhuRmx..EDeXWWri",
    likedCourses: [1],
    isVerified: true,
    role: "STUDENT",
    token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6ImJkYmU1ODAxOTg1QGNyaW5nZW1vbnN0ZXIuY29tIiwiaWF0IjoxNjk1ODAyMDc2fQ.FZCzWn0K1bhDUjDHpecqoyut0I495TH3NLGd4wk6ZCgeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiU1RVREVOVCIsImVtYWlsIjoiYmRiZTU4MDE5ODVAY3JpbmdlbW9uc3Rlci5jb20iLCJpYXQiOjE2OTU4MDIwNzZ9.HypxfsZn6hU4tUkzS0iHF0Y1wEfxNmWXCWUFMQmUYMM",
    tokenCreatedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "John",
    lastName: "Wick",
    email: "JohnWick@gmail.com",
    phoneNumber: "+37499887755",
    birthday: new Date(),
    gender: "Male",
    country: "USA",
    city: "New York",
    englishLevel: "C1",
    education: "Harvard",
    backgroundInQA: true,
    password: "$2b$10$d3ZAK4YSEfUf4PQszTO7Bea9fVes5MRiQyP4EPhuRmx..EDeXWWri",
    likedCourses: [1],
    isVerified: true,
    role: "STUDENT",
    token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJyb2xlIjoiU1RVREVOVCIsImVtYWlsIjoiNzZjNDU4MDIyMDhAYmVhY29ubWVzc2VuZ2VyLmNvbSIsImlhdCI6MTY5NTgwMjI2OH0.X40oUGqe7Og-WtfJN6ALcgbiR7TxJWW17xulzvM0mUU",
    tokenCreatedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = {
  Users,
};
